### ISSUE TITLE
Grub parameters not passing from IPXE

### ISSUE THREAD

**Issue by Soylor** [alkisg/ltsp5-uefi#2]
Hi: great project.
I've implemented your approach, but having a issue with grub.
It works but parameters are not received from ipxe

In iPXE are defined net0/rootpath and net0/filename
In grub it receives: ${net_efinet0_rootpath} ${net_efinet0_boot_file} (instead of filename)
I did an **echo** of the values in grub.conf but nothing received.

**echo "Root: " ${net_efinet0_rootpath}
echo "File: " ${net_efinet0_boot_file}
echo "File: " ${net_efinet0_filename}**

Any help with this? 
Thank you.

**Comment by alkisg** [comment]
Hi, sorry LTSP5 is no longer supported, this was a temporary project until all schools had migrated to the new LTSP, which they did.
It would take me some time to set up this again in order to be able to test it and answer the question...
