### ISSUE TITLE
Full EFI support for LTSP

### ISSUE THREAD

**Issue by Tuharsky** [alkisg/ltsp5-uefi#3]
Please, is there an official, working, documented way to enable EFI support for LTSP?

**Comment by alkisg** [comment]
LTSP supports UEFI out of the box, see the installation instructions:
https://ltsp.org/docs/installation/

This repository where you reported this bug is not the ltsp repository, you're in the wrong place.

Use https://github.com/ltsp/ltsp/discussions for ltsp discussions.
